project('nlsqlc', 'c', version: '0.1.2', default_options: ['c_std=c11', 'warning_level=3', 'werror=true'])
add_project_arguments('-Wconversion', '-Wsign-conversion', '-Wshadow', '-Wstrict-prototypes', '-Wmissing-prototypes', '-Wformat=2', '-Wundef', language: 'c')
inc = include_directories('include')
lib = library('nlsql', 'src/nlsql.c', include_directories: inc, install: true)
cli = executable('nlsqlc', 'cli/nlsqlc.c', include_directories: inc, link_with: lib)
t = executable('nlsql-tests', 'tests/test_core.c', include_directories: inc, link_with: lib)
tq = executable('nlsql-question-tests', 'tests/test_question.c', include_directories: inc, link_with: lib)
test('core', t)
test('question', tq)
install_subdir('include/nlsql', install_dir: get_option('includedir'))
