query = "(" , "nlsql" , version , query-body , ")" ;
version = "1" ;
query-body = "(" , "query" , from-clause , { join-clause } , select-clause , [ where-clause ] , [ group-clause ] , [ order-clause ] , [ limit-clause ] , ")" ;
from-clause = "(" , "from" , identifier , [ identifier ] , ")" ;
join-clause = "(" , "join" , "inner" , identifier , [ identifier ] , predicate , ")" ;
select-clause = "(" , "select" , field , { field } , ")" ;
field = "(" , "field" , expression , identifier , ")" ;
where-clause = "(" , "where" , expression , ")" ;
group-clause = "(" , "group-by" , expression , { expression } , ")" ;
order-clause = "(" , "order-by" , expression , ("asc" | "desc") , ")" ;
limit-clause = "(" , "limit" , integer , ")" ;
expression = column | parameter | reference | aggregate | predicate | arithmetic | boolean ;
column = "(" , "column" , identifier , identifier , ")" ;
parameter = "(" , "param" , identifier , identifier , ")" ;
reference = "(" , "ref" , identifier , ")" ;
aggregate = "(" , ("sum" | "avg" | "count" | "min" | "max") , expression , ")" ;
predicate = "(" , ("eq" | "gte" | "gt" | "lte" | "lt" | "neq") , expression , expression , ")" ;
arithmetic = "(" , "mul" , expression , expression , ")" ;
boolean = "(" , "and" , expression , expression , { expression } , ")" ;
identifier = letter , { letter | digit | "_" | "." } ;
integer = digit , { digit } ;
letter = "A".."Z" | "a".."z" | "_" ;
digit = "0".."9" ;
